### ISSUE TITLE
Update python version in workflows

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#1424]
We should update the python version to only those compatible with the new `xarray.DataTree`.

Most current workflows run on python 3.9, and xarray no longer support 3.9, so we should at minimum upgrade to 3.10.

## Tasks
- [x] update all workflows to use python=3.11: done via #1425.
- [x] update all workflows to use python=3.12
- [x] retire python=3.9 in testing and only support 3.10-3.12

**Comment by leewujung** [comment]
I ended up updating everything to 3.11 in #1425, but we should do another pass once 3.12 support gets online. I'll keep this open as a reminder.
