### ISSUE TITLE
Update conda recipe to be able to use setuptools_scm versioning and bump to v0.5.0

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#338]
Current recipe in https://github.com/conda-forge/echopype-feedstock will fail during building the conda package for echopype now that we are using `setuptools_scm` rather than `versioneer` for automatic versioning. This need to be updated so that it will build for v0.5.0.

### TODO
- [x] Ensure new pypi package includes `LICENSE` file.
- [x] Add `setuptools_scm >=3.4` as host requirements
- [X] Add `SETUPTOOLS_SCM_PRETEND_VERSION` as environment variable under build script
- [X] Update run requirements to match current software requirements
- [x] Re-rendered with the latest conda-smithy
- [x] Bump version to 0.5.0
- [x] Update sha256 to current package from pypi
- [x] Change build number to `0`
- [x] Add test commands
     ```yaml
       commands:
         - pip check
         - python -c "import echopype; assert echopype.__version__ != '0.0.0'"
       requires:
         - pip

**Comment by lsetiawan** [comment]
I have started these changes in 
https://github.com/conda-forge/echopype-feedstock/pull/9

**Comment by lsetiawan** [comment]
Echopype has been uploaded to `conda-forge`. Currently it is in `cf-staging` for security checks by `conda-forge` CI. https://anaconda.org/conda-forge/echopype

**Comment by leewujung** [comment]
@lsetiawan Awesome! Last issue for the v0.5.0 milestone 😀!
