### ISSUE TITLE
Refactor and clean up parsed2zarr implementation

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#966]
@lsetiawan and I talked today about refactoring and cleaning up the current parsed2zarr code. This issue is serve as a reminder for us to do this around v0.7.1 timeframe, and also as a place to link related issues/PRs/discussions.

Related issues/PRs/discussions:
- [x] #795 
- [x] #782
- [x] #777
- [x] refactor/remove `_get_complex_dataarrays` and `_get_angle_dataarrays` that are currently arbitrarily placed in `set_groups_base.py`
- [x] #1053
- [x] Remove `use_swap` arg to `open_raw`
- [x] Add `destination_path` with default `None` with an optional argument of `"swap"` which essetially make `use_swap=True`.
- [x] Check destination path so that it requires `storage_options` when it's remote file... probably already have this feature somewhere!

**Comment by leewujung** [comment]
This section of the code exposes problems in the logic where p2z object is created and then deleted and then created again, which can be changed by refactoring the class methods.
https://github.com/OSOceanAcoustics/echopype/blob/3e16b928d2bc102be3154870d6301a97359b41fe/echopype/convert/api.py#L430-L462
