### ISSUE TITLE
Priority documentation updates

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#973]
The documentation is lagging behind important developments since probably 0.6.2 or so. Let's create a list of priority gaps to address soon.

## Tasks
- [ ] Add examples on where files are saved to docs
  - see https://github.com/OSOceanAcoustics/echopype/pull/954#discussion_r1132905334 on examples already laid out in docstrings.
- [ ] Describe the use of `verbose`
- [ ] Add examples on how to pass in frequency-independent and -dependent calibration
- [x] Make sure #975 is documented if we are not able to fix the bug in v0.7.0
- [ ] Replace references to `preprocess` with `clean` or `commongrid`. Add admonition box about preprocess being deprecated
- [ ] Many of the data processing functions listed in https://github.com/OSOceanAcoustics/echopype/pull/817#issuecomment-1474564449 are missing. Add these:
  - [ ] echodata.update_platform
  - [ ] compute_Sv: Can pass env_params entries as xr.DataArrays
  - [ ] qc: exist_reversed_time and coerce_increasing_time
  - [ ] consolidate: add_location, add_depth, add_splitbeam_angle, swap_dims_channel_frequency
  - [ ] mask: frequency_differencing, apply_mask
  - [ ] commongrid: compute_NASC
- [ ] Use of Dask and delayed processing
  - [ ] With `compute_Sv`: `ds_Sv = ep.calibrate.compute_Sv(ed).compute()`
- [x] #1054 

## For later
- [ ] Add an example EK80 converted EchoData object to the doc page [raw converted data](https://echopype.readthedocs.io/en/stable/data-format-raw.html)
- [ ] Add detailed description of the `time*` determination: see https://github.com/OSOceanAcoustics/echopype/issues/656

**Comment by leewujung** [comment]
Add examples on where files are saved to docs: see https://github.com/OSOceanAcoustics/echopype/pull/954#discussion_r1132905334 on examples already laid out in docstrings.

**Comment by leewujung** [comment]
@emiliom : I decided to just edit the issue description instead of adding comments to this, so that it's easy to keep track of what's done or not.

**Comment by leewujung** [comment]
@emiliom will do the first cut on what to add for v0.7.0

**Comment by leewujung** [comment]
Most of the items in the list were added in summer 2024. I'll close this now and when we have a chance we'll add a new issue for adding other undocumented functions.
